sources:
  - sample/Sources
templates:
  - tools/sourcery/templates
output:
  sampleTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - sample
  autoMockableImports:
    - RxSwift
    - RxCocoa
