name: Deploy staging app to Firebase App Distribution
on:
  push:
    branches:
      - develop

jobs:
  deploy_android:
    name: Deploy Android app to Firebase App Distribution
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    defaults:
      run:
        working-directory: ./sample
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode buildKonfig properties
        run: echo "${{ secrets.BUILD_KONFIG_PROPERTIES }}" | base64 --decode > buildKonfig.properties

      - name: Build staging APK
        run: ./gradlew assembleStagingDebug -PversionCode=$GITHUB_RUN_NUMBER

      - name: Deploy staging to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ vars.ANDROID_FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIAL_FILE_CONTENT }}
          groups: nimble
          file: sample/android/build/outputs/apk/staging/debug/android-staging-debug.apk
