name: Test and code analysis
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Lint
        run: ./gradlew lint

      - name: Run unit tests with Kover
        run: ./gradlew koverXMLReport

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run Danger to wrap up the review
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger

  generate_sample_project:
    # The job "generate_sample_project" identify that the job "test" must complete successfully
    # before this "generate_sample_project" job will run
    needs: test
    name: Generate the sample project
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: "recursive"

      - name: Remove the old sample project
        run: rm -rf sample

      - name: Generate the new sample project
        run: ./make.sh --bundle-id co.nimble.kmm.sample --bundle-id-staging co.nimble.kmm.sample.staging --project-name sample --ios-version 14.0

      - id: changes
        name: Check for changes in the sample project
        run: |
          count=$(git status sample --porcelain | wc -l)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Commit & push the sample project changes
        if: steps.changes.outputs.count > 0
        run: |
          git config user.name team-nimblehq
          git config user.email bot@nimblehq.co
          git add sample
          git commit -m "[Chore] Generate & update sample project"
          git push
