name: Test

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
  push:
    branches-ignore:
      - develop
      - 'release/**'
      - main

jobs:
  run_unit_tests_and_review_pull_request:
    name: Review pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check out source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Lint
        run: ./gradlew lint

      - name: Run unit tests with Kover
        run: ./gradlew koverXMLReport

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run Danger to wrap up the review
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger
